language: node_js
sudo: false
dist: trusty
addons:
  chrome: stable
  safari: stable
cache:
  directories:
    - node_modules
node_js:
  - "6"
branches:
  only:
    - master
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - npm install -g gulp
script: gulp