language: node_js
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - node_modules
node_js:
  - "6"
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - env: TESTNAME='unit-tests'
    - env: TESTNAME='browser-tests'
      addons:
        sauce_connect: true
  allow_failures:
    - env: TESTNAME='browser-tests'
script: ./test.sh