language: node_js
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - node_modules
node_js:
  - "6"
branches:
  only:
    - master
before_script:
  - npm install -g gulp
script: gulp