language: node_js
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - node_modules
node_js:
  - "6"
branches:
  only:
    - master
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run test
after_script:
  - npm run codecov